name: dianminimotor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: 4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_storage: 11.6.0
  flutter:
    sdk: flutter
  flutter_popup_card: ^0.0.5
  get: 4.6.6
  google_fonts: 6.1.0
  intl: ^0.19.0
  xen_popup_card: ^0.0.3+2

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
